In [1]:
import numpy as np
import sympy as sp
from sympy import*

Matrix creation using Sympy

In [2]:
A=Matrix([[0,2],[2,3]])
A

Matrix([
[0, 2],
[2, 3]])

In [3]:
B=Matrix([[1,3],[4,3]])
B

Matrix([
[1, 3],
[4, 3]])

In [4]:
A+B

Matrix([
[1, 5],
[6, 6]])

In [5]:
A-B

Matrix([
[-1, -1],
[-2,  0]])

In [6]:
A*B

Matrix([
[ 8,  6],
[14, 15]])

In [10]:
c=sp.transpose(B)
c

Matrix([
[1, 3],
[4, 3]])

# Eigen value and Eigen vector

In [2]:
import numpy as np
from numpy import*
a = np.matrix([[0, 2], 
              [2, 3]])
w,v=np.linalg.eig(a)
print('E-value:', w)
print('E-vector', v)

E-value: [-1.  4.]
E-vector [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


In [3]:

 

mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])
 

res = np.dot(mat1,mat2)
 
 

print(res)

[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


# Diagonalization of matrix

In [23]:
M=Matrix([[1, -3, 3], [3, -5, 3], [6, -6, 4]]) 
print("Matrix : {} ".format(M))
   
 
#P, D = M.diagonalize()  
P, D=M.diagonalize()
print("Diagonal of a matrix : {}".format(D))
print("Diagonal of a matrix : {}".format(P))

Matrix : Matrix([[1, -3, 3], [3, -5, 3], [6, -6, 4]]) 
Diagonal of a matrix : Matrix([[-2, 0, 0], [0, -2, 0], [0, 0, 4]])


In [23]:
print("Diagonal of a matrix : {}".format(P))

Diagonal of a matrix : Matrix([[1, -1, 1], [1, 0, 1], [0, 1, 2]])


# Singular value decomposition

In [11]:
#Example 1
from numpy import array
from scipy.linalg import svd

A = array([[1, 2], [3, 4], [5, 6]])
print(A)
#AAT=np.dot(A,transpose(A))
U, D, VT = svd(A)
print(U)



[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]


In [12]:
print(VT)

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [13]:
print(D)

[9.52551809 0.51430058]


In [14]:

AAT=array([[5,11,17],[11,25,39],[17,39,61]])
AAT

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [15]:
e3,e4=eig(AAT)
print(e3)
print(e4)

[ 9.07354949e+01+0.j  2.64505087e-01+0.j -8.33124309e-17+0.j]
[[-0.2298477  -0.88346102  0.40824829]
 [-0.52474482 -0.24078249 -0.81649658]
 [-0.81964194  0.40189603  0.40824829]]


In [16]:
print(U)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]


In [17]:
print(D)

[9.52551809 0.51430058]


In [18]:
print(VT)

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


# Example

In [19]:
#Example 2
B=array([[1,3],[3,4],[5,7]])
B
U1, D1, VT1= svd(B)

In [36]:
print(U1)

[[-0.29240358  0.9504678  -0.10540926]
 [-0.48028559 -0.2412771  -0.84327404]
 [-0.82693766 -0.1959498   0.52704628]]


In [37]:
print(D1)

[10.40038272  0.91216191]


In [38]:
print(VT1)

[[-0.56420507 -0.82563469]
 [-0.82563469  0.56420507]]


In [13]:
b=np.matrix('1 2 3;2 4 5;3 5 6')


In [8]:
b

matrix([[1, 2, 3],
        [2, 4, 5],
        [3, 5, 6]])

In [14]:
np.linalg.inv(b)

matrix([[ 1., -3.,  2.],
        [-3.,  3., -1.],
        [ 2., -1.,  0.]])

In [32]:
c=Matrix([[6,-1],[2,3]])
p,d=c.diagonalize()

In [33]:
p

Matrix([
[1, 1],
[2, 1]])

In [34]:
d

Matrix([
[4, 0],
[0, 5]])

In [51]:
c=np.matrix([[4,0],[3,-5]])
ei,eiv=np.linalg.eig(c)

In [52]:
c

matrix([[ 4,  0],
        [ 3, -5]])

In [53]:
ei

array([-5.,  4.])

In [37]:
eiv

matrix([[0.70710678, 0.4472136 ],
        [0.70710678, 0.89442719]])

In [40]:
c1=np.matrix([[4,0],[3,-5]])
c1

matrix([[ 4,  0],
        [ 3, -5]])

In [42]:
s,d,v=np.linalg.svd(c1)
s

matrix([[-0.4472136 , -0.89442719],
        [-0.89442719,  0.4472136 ]])

In [43]:
d

array([6.32455532, 3.16227766])

In [44]:
v

matrix([[-0.70710678,  0.70710678],
        [-0.70710678, -0.70710678]])

In [71]:
U=np.matrix([[1,2],[2,-1]])
d=np.matrix([[sqrt(40),0],[0,sqrt(10)]])
r=np.matrix([[1,-1],[1,1]])

In [72]:
f=U*d*r

In [73]:
f

matrix([[4*sqrt(10), 0],
        [3*sqrt(10), -5*sqrt(10)]], dtype=object)

In [12]:
#Example 1
from numpy import array
from scipy.linalg import svd

A = array([[3,1,1], [-1,3,1]])
print(A)
#AAT=np.dot(A,transpose(A))
U, D, VT = svd(A)
#Example 2
from numpy import*
from scipy.linalg import svd

A = array([[1, 2], [3, 4], [5, 6]])
print(A)
#AAT=np.dot(A,transpose(A))
U, D, VT = svd(A)
print(U)


[[ 3  1  1]
 [-1  3  1]]
[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]


array([9.52551809, 0.51430058])

In [13]:
print(D)

[9.52551809 0.51430058]


In [10]:
D1=matrix([[D[0], 0], [0, D[1]], [0,0 ]])
U1=matrix(U)
VT1=matrix(VT)
D1

matrix([[9.52551809, 0.        ],
        [0.        , 0.51430058],
        [0.        , 0.        ]])

In [11]:
print(U1*D1*VT1)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [3]:
print(VT)

[[ 4.08248290e-01  8.16496581e-01  4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  8.32667268e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]


In [4]:
1/6**0.5

0.4082482904638631

In [5]:
-5/30**0.5

-0.9128709291752769